### PR TITLE
Chore/fix: enable JSX/TSX linting

### LINKED ISSUE #218: estling config shoudl not all allow fetch without await
### Description

This should not pass the ESLint check because fetch is asynchronous but not awaited, so "result" is an unhandled Promise, not the actual response object
```
useEffect(() => {
		try {
			const result = fetch('/api/auth/valid-reset-pw-token', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json'
				},
				body: JSON.stringify(token)
			});
			if (!result) {
				setIsValidToken(false);
			}

			setIsValidToken(true);
		} catch (error) {
			console.error(error);
		}
		
	}, []);
```

### PR DESCRIPTION
**Pull request by madcampos**
## Summary

Enables linting for `.jsx` and `.tsx` files that was disabled before.

## Tests

Re-linted the project and fixed issues.

## Additional information

I've fixed all of the linting errors and some of the warnings as well.

### CODE REVIEW

File: src/components/CompleteProfile/CompleteProfile.tsx [hunk 1]
```diff
@@ -72,7 +72,8 @@ const isRealDate = (birthday: string): boolean => {
 	const month = Number(monthStr);
 	const day = Number(dayStr);
 
-	const date = new Date(2000, month - 1, day);
+	const REFERENCE_YEAR = 2000;
+	const date = new Date(REFERENCE_YEAR, month - 1, day);
```
Comment (bcha92) [inline src/components/CompleteProfile/CompleteProfile.tsx:76]: Is a separate `REFERENCE_YEAR` variable needed for any reason?
Or is it just for naming convention clarity?

**Review by bcha92 — COMMENTED** [review]
not a blocker

**Review by sounmind — APPROVED** [review]
LGTM!

File: src/components/CompleteProfile/CompleteProfile.tsx (hunk 1 above)
Comment (madcampos) [reply src/components/CompleteProfile/CompleteProfile.tsx:76]: Just for clarity. It shuts up the linting warning for magic numbers. Random numbers without an explanation of what they mean are usually a bad idea as the context of what something like "1234" means

**Review by kbventures — APPROVED** [review]
Great work. Ready to be merged!
