### PR TITLE
Chore: fix failing tests

### LINKED ISSUE #122: Add a hard limit to text fields
Right now, the backend accepts any arbitrarily long data. We want to impose a hard limit on input fields so the api is not abused.

This should apply to any `string` field, and be one of two types:
- Short text (data coming from `input` fields): 1024 characters
- Long text (data coming from `textarea` fields): 16 * 1024 characters = 16kb

This limits can be implemented using [Zod's string methods](https://zod.dev/api?id=strings).

We would also like to add a general hard limit for the whole request. So the api is not abused by very large requests.

The limit should allow for a good amount of data to be transmitted, yet, block very large requests, so a limit of 48kb seems adequate as it allows for anequivalent of 3 large text fields and we predict no more than one large field per schema, leaving enough room for all fields.

This can be implemented using the [Hono `body-limit` middleware](https://hono.dev/docs/middleware/builtin/body-limit).

### LINKED ISSUE #200: [BUG]: GET team members endpoint returns incorrect information
### Description

The data returned by the GET team members endpoint is incorrect. It should return the role name and id.

### Steps to Reproduce

1. Send a request to the GET team members endpoint
2. Check the `id` and `name` fields
3. They don't match the role id and name

### Expected Behavior

This endpoint should expose the role name and id.

### Screenshots (if applicable)

_No response_

### Operating System

N/A

### Browser

N/A

### Browser Version

latest

### Additional Information

_No response_

### LINKED ISSUE #201: [BUG]:  Trying to delete a team member that is not part of the team should return an error
### Description

Trying to delete a team member that is not part of the team should return an error. Instead it is returning a success response.

### Steps to Reproduce

1. Send a request to the DELETE team members endpoint with a user that is not part of the team.
2. Success response

### Expected Behavior

This endpoint should return an error if the user is not part of the team.

### Screenshots (if applicable)

_No response_

### Operating System

N/A

### Browser

N/A

### Browser Version

latest

### Additional Information

_No response_

### LINKED ISSUE #202: [BUG]: Adding team member with wrong ID should return error
### Description

Trying to add a team member with an invalid ID should return an error. Instead it is returning a success response.

### Steps to Reproduce

1. Send a request to the POST team members endpoint with an invalid user id.
2. Success response

### Expected Behavior

This endpoint should return an error if the user is not part of the team.

### Screenshots (if applicable)

_No response_

### Operating System

N/A

### Browser

N/A

### Browser Version

latest

### Additional Information

_No response_

### LINKED ISSUE #203: [BUG]: Updating a team member's description is failing
### Description

Trying to update a team member with a description fails with a 422 error.

### Steps to Reproduce

1. Send a request to the PATCH team members endpoint with the description field.
2. 422 response

### Expected Behavior

This endpoint should return a success for valid descriptions.

### Screenshots (if applicable)

_No response_

### Operating System

N/A

### Browser

N/A

### Browser Version

latest

### Additional Information

_No response_

### LINKED ISSUE #204: [BUG]: Team names should be unique
### Description

Trying to create a new team with the same name is a success. It should block a team with the same name as an active (i.e. not deleted) team to exist.

### Steps to Reproduce

1. Send a request to the POST team.
2. Send a new request with the same name
3. Team is created

### Expected Behavior

Active team names should be unique.

### Screenshots (if applicable)

_No response_

### Operating System

N/A

### Browser

N/A

### Browser Version

latest

### Additional Information

_No response_

### LINKED ISSUE #205: [BUG]: Getting team members for an invalid team id shoudl return an error
### Description

Trying to get the team members for a team that does not exist should return an error.

### Steps to Reproduce

1. Send a request to the GET team members with an invalid team id.
2. Success response

### Expected Behavior

If the team does not exist, the members request should fail.

### Screenshots (if applicable)

_No response_

### Operating System

N/A

### Browser

N/A

### Browser Version

latest

### Additional Information

_No response_

### LINKED ISSUE #206: [BUG]: Organizers should be able to create teams
### Description

Organizers can't create new teams.

### Steps to Reproduce

1. Log-in with an organizer account
2. Try to create a new team
3. Error

### Expected Behavior

Organiers should be able to create teams

### Screenshots (if applicable)

_No response_

### Operating System

N/A

### Browser

N/A

### Browser Version

latest

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by madcampos**
## Additional information

Resolves: #200, #201, #202, #203, #204, #205, #206

### CODE REVIEW

File: api/src/middleware/body-size.ts [hunk 1]
```diff
@@ -0,0 +1,26 @@
+/* eslint-disable @typescript-eslint/no-magic-numbers */
+
+import { bodyLimit } from 'hono/body-limit';
+import { StatusCodes, type StatusResponse } from '../utils/responses.ts';
+
+/** 48kb */
+const TOTAL_FILE_SIZE_IN_KB = 48 * 1024;
+
+/** 512kb */
+const FILE_UPLOAD_SIZE_IN_KB = 512 * 1024;
```
Comment (manvinderjit) [inline api/src/middleware/body-size.ts]: question: Is this for the whole project? Because in the file upload issue specs, we have specified 5MB limit for upload file.

image

File: api/src/routes/auth/validation.ts [hunk 2]
```diff
@@ -46,11 +50,13 @@ export type Access = z.infer<typeof AccessSchema>;
 export const SignInSchema = z.object({
 	email: z
 		.email('Invalid Email')
+		.max(SHORT_TEXT_SIZE_IN_CHAR)
 		.trim()
```
Comment (manvinderjit) [inline api/src/routes/auth/validation.ts]: suggestion: trim before determining min/max

File: api/src/routes/auth/validation.ts [hunk 3]
```diff
@@ -46,11 +50,13 @@ export type Access = z.infer<typeof AccessSchema>;
...
 		.toLowerCase()
 		.min(1, 'Email must be at least one character long'),
 	password: z
 		.string()
+		.max(SHORT_TEXT_SIZE_IN_CHAR)
 		.trim()
```
Comment (manvinderjit) [inline api/src/routes/auth/validation.ts]: suggestion: trim before determining min/max

File: api/src/routes/auth/validation.ts [hunk 4]
```diff
@@ -60,15 +66,18 @@ export type SignInData = z.infer<typeof SignInSchema>;
 export const SignUpSchema = z.object({
 	name: z
 		.string({ error: 'Name is required' })
+		.max(SHORT_TEXT_SIZE_IN_CHAR)
 		.trim()
```
Comment (manvinderjit) [inline api/src/routes/auth/validation.ts]: suggestion: trim before determining min/max

File: api/src/routes/event-log/validation.ts [hunk 5]
```diff
@@ -22,6 +23,7 @@ export const EventLogSchema = IdAndSchemaVersionSchema
 			subjectSource: LogItemSourceSchema,
 			verb: z
 				.string()
+				.max(SHORT_TEXT_SIZE_IN_CHAR)
 				.trim()
```
Comment (manvinderjit) [inline api/src/routes/event-log/validation.ts:32]: suggestion: trim before determining min/max

File: api/src/routes/profile/validation.ts [hunk 6]
```diff
@@ -12,16 +13,19 @@ export const ProfileSchema = BaseDbEntitySchema.extend(
 	z.object({
 		email: z
 			.email('Invalid Email.')
+			.max(SHORT_TEXT_SIZE_IN_CHAR)
 			.trim()
```
Comment (manvinderjit) [inline api/src/routes/profile/validation.ts:45]: suggestion: trim before max/min

File: api/src/routes/team/index.ts [hunk 7]
```diff
@@ -223,6 +239,14 @@ teamRoutes.openapi(
 			return context.json({ message: 'Team not found' } satisfies StatusResponse, StatusCodes.NOT_FOUND);
 		}
 
+		if (body.name) {
+			const hasExistingTeamName = await doestSameTeamNameExist(context.env.Database, body.name);
```
Comment (manvinderjit) [inline api/src/routes/team/index.ts]: typo: 
```suggestion
			const hasExistingTeamName = await doesSameTeamNameExist(context.env.Database, body.name);
```

File: api/src/routes/team/validation.ts [hunk 8]
```diff
@@ -1,15 +1,18 @@
 import { z } from 'zod';
+import { LONG_TEXT_SIZE_IN_CHAR, SHORT_TEXT_SIZE_IN_CHAR } from '../../middleware/body-size.ts';
 import { BaseDbEntitySchema, BaseDBFieldsToOmit } from '../../utils/db.ts';
 
 export const TeamSchema = BaseDbEntitySchema.extend(
 	z.object({
 		name: z
 			.string()
+			.max(SHORT_TEXT_SIZE_IN_CHAR)
 			.trim()
```
Comment (manvinderjit) [inline api/src/routes/team/validation.ts:9]: suggestions: trim before min/max

**Review by manvinderjit — DISMISSED** [review]
@madcampos Thank you for all the effort. I left minor suggestions and couple of clarifications.

File: api/src/middleware/body-size.ts (hunk 1 above)
Comment (madcampos) [reply api/src/middleware/body-size.ts]: I'll fix that, the size is wrong here.

**Review by manvinderjit — APPROVED** [review]

File: api/src/middleware/body-size.ts [hunk 9]
```diff
@@ -0,0 +1,26 @@
+/* eslint-disable @typescript-eslint/no-magic-numbers */
+
+import { bodyLimit } from 'hono/body-limit';
+import { StatusCodes, type StatusResponse } from '../utils/responses.ts';
+
+/** 48kb */
```
Comment (kbventures) [inline api/src/middleware/body-size.ts:6]: Nitpick: KiB, not KB.  1KB 1000 bytes, while 1 KiB is 1014bytes.

Question: What is the rationale/source for choosing these specific metrics for protecting the endpoint?

File: api/src/routes/profile/data.ts [hunk 10]
```diff
@@ -29,6 +29,22 @@ export async function doesProfileExist(database: D1Database, id: string) {
 	return Boolean(profile);
 }
 
+export async function nonExistingProfileIds(database: D1Database, ids: string[]) {
```
Comment (kbventures) [inline api/src/routes/profile/data.ts:32]: Question:

nonExistingProfileIds ???

File: api/src/routes/team-members/data.ts [hunk 11]
```diff
@@ -1,7 +1,24 @@
 import { DBTables, generateBaseDBfields } from '../../utils/db.ts';
 import { EventLog } from '../event-log/data.ts';
-import type { Profile } from '../profile/validation.ts';
-import type { AddTeamMembers, UpdateTeamMembers } from './validation.ts';
+import type { AddTeamMembers, TeamMemberInfo, UpdateTeamMembers } from './validation.ts';
+
+export async function nonExistingTeamMemberIds(database: D1Database, teamId: string, ids: string[]) {
```
Comment (kbventures) [inline api/src/routes/team-members/data.ts:5]: Same as the previous question...nonExistingTeamMembberIds seems contradictory and a question in itself..

**Review by kbventures — APPROVED** [review]
Great work. Some notes around body limit middleware sizes decisions would be nice.

File: api/src/middleware/body-size.ts (hunk 9 above)
Comment (madcampos) [reply api/src/middleware/body-size.ts:6]: Regarding KB vs KiB:

Meme from Futurama with the caption: You are technically correct, the best kind of correct.

While yes, you are correct, I prefer keeping the same naming as in this context, it doesn't make a difference if we are using one unit or another. Plus, people are more used to file sizes being in KB rather than in KiB.

As for the specific values, here are the references:
- https://github.com/torontojs/communityhub/issues/122
- https://github.com/torontojs/communityhub/issues/98#issuecomment-2933030822

File: api/src/routes/profile/data.ts (hunk 10 above)
Comment (madcampos) [reply api/src/routes/profile/data.ts:32]: It checks the database for profile ids that do not exist, if you pass a random uuid that is not on the database, this will tell you it is not there. Should the function be renamed?
